

#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#include <stdio.h>
#include <SDL2/SDL.h>
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <vector>

#define SCREEN_X 1000
#define SCREEN_Y 1000

#define UNIVERSE_DAMAGE 0.2
#define LARTICLES_MAX 1200
#define LARTICLES_START_AMOUNT 700
#define UNIVERSE_SIZE 4500.0
#define LARTICLE_COLISSION_MULTIPLYER 1.02
#define UNIVERSE_FORCE 500000000.0
#define UNIVERSE_FRICTION 0.01
#define UNIVERSE_GRAVITY_WELL 200.0

#define LARTICLE_SPLIT_HEALTH 1100.0
#define LARTICLE_TIME 500
#define LARTICLE_INITIATE_TIME LARTICLE_TIME * 8 / 10
#define LARTICLE_SPEED 0.1
#define LARTICLE_MAX_SPEED 2.0
#define LARTICLE_SIZE 10.0
#define LARTICLE_MAX_HEALTH 2000.0
#define LARTICLE_MAX_ANGLE_SPEED 3.14/24.0
#define LARTICLE_EAT_ANGLE M_PI / 16.0
#define LARTICLE_EAT_DAMAGE LARTICLE_MAX_HEALTH / 7.0
#define LARTICLE_EAT_PERCENTAGE 0.9
#define LARTICLE_ATTACK_DAMAGE LARTICLE_EAT_DAMAGE/2.5
#define LARTICLES_REGEN 1.0
#define LARTICLES_SPEED_MULTIPLIER 1.3

#define LARTICLE_START_CONNECTIONS 30

#define LARTICLE_VISUAL_RANGE LARTICLE_SIZE * 35
#define LARTICLE_SIZE_SCALE 10
#define LARTICLE_FOV M_PI/12.0

#define NEURONS_START_POTENTIAL 0.0
#define NEURONS_AMOUNT 50
#define NEURONS_CONNECTIONS 100
#define NEURONS_WEIGHT_SIZE 100
#define NEURONS_WEIGHT_SCALE 33
#define NEURONS_LEARNINGRATE 1
#define NEURON_MUTATIONRATE 5

#define NEURON_MOVE_X 0
#define NEURON_MOVE_Y 1
#define NEURON_MOVE_ANGLE 2
#define NEURON_ATTACK 3
#define NEURON_EAT 4
#define NEURON_SPLIT 5
#define NEURON_ALIVE_1 6
#define NEURON_ALIVE_2 38
#define NEURON_STATE_1 7
#define NEURON_STATE_2 8
#define NEURON_STATE_3 9
#define NEURON_FIELD_ANGLE 10
#define NEURON_FIELD_DISTANCE 11
#define NEURON_SEE 12
#define NEURON_SEE_ANGLE 13
#define NEURON_SEE_HEALTH 14
#define NEURON_SEE_STATE_1 15
#define NEURON_SEE_STATE_2 16
#define NEURON_SEE_STATE_3 17
#define NEURON_SEE_GRAVITY 18
#define NEURON_SEE_DISTANCE_1 19
#define NEURON_SEE_DISTANCE_2 36
#define NEURON_SENSE_GRAVITY 20
#define NEURON_SENSE_GRAVITY_ANGLE 21
#define NEURON_SENSE_ANGLE 22
#define NEURON_SENSE_HEALTH 23
#define NEURON_IN_1 24
#define NEURON_IN_2 25
#define NEURON_IN_3 35
#define NEURON_OUT_1 26
#define NEURON_OUT_2 27
#define NEURON_OUT_3 34
#define NEURON_SPEAK_1 28
#define NEURON_SPEAK_2 29
#define NEURON_SPEAK_3 30
#define NEURON_HEAR_1 31
#define NEURON_HEAR_2 32
#define NEURON_HEAR_3 33
#define NEURON_SINE_1 37


//#define WIDTH 1800
//#define HEIGHT 1200

#endif
